import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  env: {
    NEXT_PUBLIC_MIDDLEWARE_URL: process.env.NEXT_PUBLIC_MIDDLEWARE_URL ?? "http://localhost:3001",
    NEXT_PUBLIC_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS ?? "CCRJTH7RJLNTXQYTMNSXZZRVGFDIAXDAOYNVSROPDUJ3BVVATNUSNPE6",
    NEXT_PUBLIC_PRIVACY_POOL_ADDRESS: process.env.NEXT_PUBLIC_PRIVACY_POOL_ADDRESS ?? "CAL6DU3Z5UR7WTDWKTBCT5DQF23CXJTDIN5AY6BQFRER5CFFGT6SDFFF",
  },
};

export default nextConfig;
